[colors]
foreground = "#c9c7cd"
background = "#161617"
cursor_bg = "#e3e2e5"
cursor_border = "#e3e2e5"
cursor_fg = "#161617"
selection_bg = "#3c3b3e"
selection_fg = "#e3e2e5"
scrollbar_thumb = "#57575f"
split = "#57575f"
ansi = ["#27272a", "#ea83a5", "#90b99f", "#e6b99d", "#92a2d5", "#e29eca", "#85b5ba", "#c1c0d4"]
brights = ["#353539", "#ed96b3", "#a7c8b3", "#eac5ae", "#a7b3dd", "#e8b0d4", "#97c0c4", "#cac9dd"]
