# preload = ~/dotfiles/backgrounds/firewatch.jpg
# wallpaper = DP-1,~/dotfiles/backgrounds/firewatch.jpg
# splash = false

wallpaper {
  monitor = DP-1
  path = ~/dotfiles/backgrounds/doom.jpg
  fit_mode = cover
}

splash = false
