# Display Settings
monitor = eDP-1, 1920x1080@60, auto, 1
monitor = DP-1, 1920x1080@60, auto, 1, mirror, eDP-1
monitor = DP-5, 1920x1080@60, auto, 1, mirror, eDP-1

# Apps to be executed on launch
# exec-once = /usr/lib/pam_kwallet_init
exec-once = nm-applet
exec-once = waybar
exec-once = hypridle
exec-once = tmux setenv -g HYPRLAND_INSTANCE_SIGNATURE "$HYPRLAND_INSTANCE_SIGNATURE"
exec-once = hyprpaper -n
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & udiskie

# exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# GIF wallpaper
# exec-once = swww-daemon
# exec-once = swww img /home/ewiens/dotfiles/backgrounds/animated/japanrain.gif

# Extra files
source = ~/.config/hypr/binds.conf

# NVIDIA settings
# env = XDG_SESSION_TYPE,wayland

# Environment Settings
env = HYPRCURSOR_THEME,Posys-Cursor-Scalable-Black
env = HYPRCURSOR_SIZE,24

# Settings related to input devs
input {
    kb_layout = us
    follow_mouse = true
    sensitivity = 0.2
    repeat_rate = 45
    repeat_delay = 450

    touchpad {
        natural_scroll = true
        scroll_factor = 0.3
        tap-to-click = false
        clickfinger_behavior = 1
    }
}

gestures {
    workspace_swipe = true
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 1
    col.active_border = rgb(d1d5db) 45deg
    col.inactive_border = rgba(121212cc)

    layout = master #master
}

decoration {
    rounding = 4

    blur {
        enabled = true
        size = 9
        passes = 3
        ignore_opacity = true
    }

    shadow {
        enabled = true
        range = 10
    }

    active_opacity = 1
    inactive_opacity = 0.9
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsIn, 1, 7, myBezier, slide
    animation = windowsOut, 1, 7, default, slide
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default, slidefade 20%
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    animate_mouse_windowdragging = true
    disable_hyprland_logo = true
    disable_splash_rendering = true
    enable_swallow = true
    # render_ahead_safezone = 3
}

# windowrulev2=fakefullscreen, class:^(code-url-handler)$

