# preload = ~/dotfiles/backgrounds/firewatch.jpg
# wallpaper = eDP-1,~/dotfiles/backgrounds/firewatch.jpg
# splash = false

wallpaper {
  monitor = eDP-1
  path = ~/dotfiles/backgrounds/firewatch.jpg
  fit_mode = cover
}

splash = false
