-- Auto Enable Tree-sitter Highlights + Indents
-- vim.api.nvim_create_autocmd('FileType', {
--   pattern = {
--     'go',
--     'java',
--     'javascript',
--     'javascriptreact',
--     'json',
--     'lua',
--     'python',
--     'sh',
--     'typescript',
--     'typescriptreact'
--   },
--   callback = function()
--     vim.treesitter.start()
--     vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
--   end
-- })
